CREATE TABLE IF NOT EXISTS "User" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "Todo" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Info"	INTEGER NOT NULL,
	"UserID"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("UserID") REFERENCES "User"("ID") ON DELETE CASCADE
);
